name: shoply
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  lottie: ^3.2.0
  shared_preferences: ^2.5.2
  get_it: ^7.6.7
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/lottie/
  
  fonts: 
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
          style: italic
        - asset: assets/fonts/Switzer-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Bold.otf
          style: italic
        - asset: assets/fonts/Switzer-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extrabold.otf
          style: italic
        - asset: assets/fonts/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extralight.otf
          style: italic
        - asset: assets/fonts/Switzer-ExtralightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Italic.otf
          style: italic
        - asset: assets/fonts/Switzer-Light.otf
          style: italic
        - asset: assets/fonts/Switzer-LightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Medium.otf
          style: italic
        - asset: assets/fonts/Switzer-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Regular.otf
          style: normal
        - asset: assets/fonts/Switzer-SemiBold.otf
          style: italic
        - asset: assets/fonts/Switzer-SemiBoldItalic.otf
          style: italic
